// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpR0ODVqmwymErSSrgUQAON1XeDANJTk4',
    appId: '1:359469852205:android:882f72b1838b0b962e3aa4',
    messagingSenderId: '359469852205',
    projectId: 'intelivita-chat-app',
    databaseURL: 'https://intelivita-chat-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intelivita-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_g_Rm0oA2DbM-SLxInpageCfgdD_X9WA',
    appId: '1:359469852205:ios:e13a7ac8e5d76ac92e3aa4',
    messagingSenderId: '359469852205',
    projectId: 'intelivita-chat-app',
    databaseURL: 'https://intelivita-chat-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'intelivita-chat-app.appspot.com',
    androidClientId: '359469852205-13656a6190k7cuf1e1fiktm6n93nfqrg.apps.googleusercontent.com',
    iosClientId: '359469852205-2tdasr2l51qsbnlm7529v1k0bplb7eea.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelivitaChatApp',
  );
}
